### ISSUE TITLE
BfA: DK Runes working, but error on registering

### ISSUE THREAD

**Issue by nyyr** [nyyr/ArcHUD3#25]
1x ...ceArcHUD3\Libs\AceEvent-3.0\AceEvent-3.0-4.lua:33: Attempt to register unknown event "RUNE_TYPE_UPDATE"

**Comment by Chickenchasr** [comment]
Hi, I think in bfa they changed the register event to give out an error on unexisting events, so they might have changed the "RUNE_TYPE_UPDATE" event, without documenting it in the api changes. While we're at it, there is one more documented change they changed "UNIT_POWER" to "UNIT_POWER_UPDATE" and this too can affect quite some rings.

Cheers, 
Garrett
