### ISSUE TITLE
attempt to index local 'color' (a nil value)

### ISSUE THREAD

**Issue by swe-pawe** [nyyr/ArcHUD3#34]
I'm getting the following Error on patch 8:

Message: Interface\AddOns\ArcHUD3\Core.lua:710: attempt to index local 'color' (a nil value)
Time: Wed Jul 18 21:02:29 2018
Count: 7
Stack: Interface\AddOns\ArcHUD3\Core.lua:710: attempt to index local 'color' (a nil value)
(tail call): ?
Interface\AddOns\ArcHUD3\Core.lua:710: in function `?'
...UD3\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:145: in function <...UD3\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:145>
[string "safecall Dispatcher[2]"]:4: in function <[string "safecall Dispatcher[2]"]:4>
[C]: ?
[string "safecall Dispatcher[2]"]:13: in function `?'
...UD3\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90: in function `Fire'
...ce\AddOns\ArcHUD3\Libs\AceEvent-3.0\AceEvent-3.0.lua:120: in function <...ce\AddOns\ArcHUD3\Libs\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: <none>

Is this already fixed in branch "wow8"?

Best regards

**Comment by nyyr** [comment]
Please recheck with the new release, I now merged wow8 into master

**Comment by swe-pawe** [comment]
Checked - issue is fixed with release 5.0.0.

Thx and btw.: good job - thank you
