### ISSUE TITLE
Combo Point/Soul Shard Numeric Indicator

### ISSUE THREAD

**Issue by Collin530** [nyyr/ArcHUD3#35]
I was sad to see the numeric indicator for combo points and soul shards removed.  I appreciated the simplicity of readability that this feature offered, and was wondering if it could be re-implemented in a future build.  Thanks!

**Comment by nyyr** [comment]
Oh, it's actually not gone, it has just moved: Just enable the related Arc/Ring and select "Show huge text":
![grafik](https://user-images.githubusercontent.com/38923070/42959704-fd2a78b0-8b89-11e8-8346-9f03e5c3a8cf.png)
