### ISSUE TITLE
Arc for specific buff/debuff (remaining time & stacks)

### ISSUE THREAD

**Issue by Cisira** [nyyr/ArcHUD3#36]
I really would like to have the option to enable specific buffs or just buffs under <15sec to be displayed left to the destination frame. I have to keep up 3 Stacks with my Pet Hunter for the 9% Crit buff and this would help a lot to have it visually right in front of me. Its a pain watchin always the top right for it and then gettin set to refresh it.

**Comment by nyyr** [comment]
That is actually already possible with the Custom Buff Arcs:
![grafik](https://user-images.githubusercontent.com/38923070/42960198-63689584-8b8b-11e8-8d08-ec0bc31b21c5.png)

Please check if that works for you.

**Comment by Cisira** [comment]
Yes but only problem with this is, that it shows me when i reached 3 stacks but i want to know the duration of the buff. Like a decreasing Arc for that 8 Seconds. Is that also Possible?

**Comment by nyyr** [comment]
That works, too: Untick "Use stack applications" and set "Maximum size" to 1:
![grafik](https://user-images.githubusercontent.com/38923070/42967907-00df94e6-8ba2-11e8-9bfe-e8e9390fd8d5.png)

**Comment by Cisira** [comment]
Thats it! Thanks a lot, now i know how to configure even more with this pure genius addon, Thanks!
