### ISSUE TITLE
Fade option bug

### ISSUE THREAD

**Issue by Akrololz** [nyyr/ArcHUD3#37]
Hey! I've used this addon for ages, and after version **v4.2.3** this addon have a bug, fade option is working wrong on every version after **v4.2.3**, so the bug is - when u cancel auto attacks, addon fade arcs like he fade it when u have option "When full". So basically, **v4.2.3** and earlier versions - when u cancel auto attack arc still standing as option "In combat", and he fades to "When full" only when u leave combat, because out of combat is the second for a priority option, and after **v4.2.3** this option is bugged, and addon counting out of combat option when u just  cancel autoattacks (or just press ESC). Same if you will just target some1 and will press autoattack, addon will pop fade option "In combat", even if youre not in combat (just by rightclicking on some1 and not hitting him won't put you in combat, but fade option work like youre in combat).  Please fix that, I'm a biggest fun of that addon :)

**Comment by Akrololz** [comment]
think i found solution, at least on dummy it worked, new  **CombatStatus()** in all versions after v4.2.3 seems broken, so i just tooked combat status from 4.2.3 which is :

> ----------------------------------------------
> -- CombatStatus()
> ----------------------------------------------
> function ArcHUD:CombatStatus(event)
> 	--self:LevelDebug(d_info, "CombatStatus: event = " .. event)
> 
> 	if(event == "PLAYER_ENTER_COMBAT" or event == "PLAYER_REGEN_DISABLED") then
> 		self.PlayerIsInCombat = true
> 		if(event == "PLAYER_REGEN_DISABLED") then
> 			self.PlayerIsRegenOn = false
> 		end
> 	elseif(event == "PLAYER_LEAVE_COMBAT" or event == "PLAYER_REGEN_ENABLED") then
> 		if(event == "PLAYER_LEAVE_COMBAT" and self.PlayerIsRegenOn) then
> 			self.PlayerIsInCombat = false
> 		elseif(event == "PLAYER_REGEN_ENABLED") then
> 			self.PlayerIsInCombat = false
> 			self.PlayerIsRegenOn = true
> 		end
> 	elseif(event == "PET_ATTACK_START") then
> 		self.PetIsInCombat = true
> 	elseif(event == "PET_ATTACK_STOP") then
> 		self.PetIsInCombat = false
> 	end
> end

and changed it in new version, worked for me

**Comment by nyyr** [comment]
Fixed with v5.0.3
