### ISSUE TITLE
Error - classic-v5.0.6

### ISSUE THREAD

**Issue by daberniegithub** [nyyr/ArcHUD3#38]
Message: Interface\AddOns\ArcHUD3-classic\BlizzardFrames.lua:15: attempt to index global 'RuneFrame' (a nil value)
Time: Tue Sep  3 17:21:00 2019
Count: 1
Stack: Interface\AddOns\ArcHUD3-classic\BlizzardFrames.lua:15: attempt to index global 'RuneFrame' (a nil value)
Interface\AddOns\ArcHUD3-classic\BlizzardFrames.lua:15: in function `HideBlizzardPlayer'
Interface\AddOns\ArcHUD3-classic\Core.lua:299: in function `OnProfileChanged'
Interface\AddOns\ArcHUD3-classic\Core.lua:228: in function <Interface\AddOns\ArcHUD3-classic\Core.lua:195>
[C]: ?
...s\ArcHUD3-classic\Libs\AceAddon-3.0\AceAddon-3.0.lua:70: in function <...s\ArcHUD3-classic\Libs\AceAddon-3.0\AceAddon-3.0.lua:65>
...s\ArcHUD3-classic\Libs\AceAddon-3.0\AceAddon-3.0.lua:527: in function `EnableAddon'
...s\ArcHUD3-classic\Libs\AceAddon-3.0\AceAddon-3.0.lua:620: in function <...s\ArcHUD3-classic\Libs\AceAddon-3.0\AceAddon-3.0.lua:605>
[C]: in function `LoadAddOn'
Interface\FrameXML\UIParent.lua:353: in function `UIParentLoadAddOn'
Interface\FrameXML\UIParent.lua:380: in function `CombatLog_LoadUI'
Interface\FrameXML\UIParent.lua:695: in function <Interface\FrameXML\UIParent.lua:658>

Locals: <none>

**Comment by nyyr** [comment]
A assume this only happens when hiding the Player Frame via the ArcHUD3 Options / Misc? If not, please be more descriptive on when this error happens.

**Comment by daberniegithub** [comment]
Your assumption is correct. ;D

**Comment by daberniegithub** [comment]
thanks for your work ! I love the arcs and I dont care about the blizz frames at all.
