### ISSUE TITLE
RU localization error

### ISSUE THREAD

**Issue by Taresgos** [nyyr/ArcHUD3#39]
its actually a bug more than 1 year, sad that no one except me reported that)
On a russian client there is empty list in ingame addon settings menu:  >settings - >module settings. Attached a screenshot
![image](https://user-images.githubusercontent.com/54892371/64249911-7aa2c680-cf1d-11e9-9b90-a7d0ea736692.png)
It is like this since v. 5.0.1 _on both retail and classic_. 
But i have a solution that works perfect for me - in folder C:\World of Warcraft\_classic_\Interface\AddOns\ArcHUD3-classic\Locales i delete all locales files except enUS.lua and change 2 lines in enUS.lua:  
start with
- L["FONT"]

- LM["FONT"]
in both i change "FRIZQT__.TTF" to "FRIZQT___CYR.TTF"  (yes, with 3 "_" instead of 2)
and see what happens on a screenshot: it work!
![image](https://user-images.githubusercontent.com/54892371/64250880-e71ec500-cf1f-11e9-978c-f09a7e42b7fb.png)

Also i can admit that russian translate have some typo errors and some non-translated strings and btw there is easy english and i dont think it need to be translated because all technical texts (such as setting description and so on) much more clear in english than on russian translation.
So you may be can just add a fixed locale file to package

**Comment by nyyr** [comment]
Mhm, this might be true if you know English - so I'm a bit reluctant to remove the translation completely. You are invited to provided fixes to the translation ;-)

The font seems to be correctly set to FRIZQT___CYR.TTF in ruRU.lua. Do you get any exceptions / LUA errors (maybe during login or when openening the Config dialog)? If the config is missing completely, it is likely that something went wrong - this could be a missing key. This should be visible as LUA error then.

**Comment by nyyr** [comment]
I indeed found some missing keys in the Russian translation. I added them and committed them, can you check whether this fixes your issue (either on classic or live)? It should be sufficient to replace your ruRU.lua file with the one in current master or classic branch.

**Comment by Taresgos** [comment]
Yes, now it works! Also i did some translation fixes and send them here #41 :)

**Comment by nyyr** [comment]
Thanks for the update, I merged it and made a new release: v5.0.9
