### ISSUE TITLE
classic-v5.0.10 errors

### ISSUE THREAD

**Issue by Villainess** [nyyr/ArcHUD3#43]
Stoked to have ArcHUD back for Classic (especially the pet happiness!), but I seem to have the same two errors upon logging in:
```
2x ...s\ArcHUD3-classic\Libs\AceEvent-3.0\AceEvent-3.0-4.lua:33: Attempt to register unknown event "PLAYER_SPECIALIZATION_CHANGED"
[C]: in function `RegisterEvent'
...s\ArcHUD3-classic\Libs\AceEvent-3.0\AceEvent-3.0-4.lua:33: in function `OnUsed'
...sic\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:142: in function `RegisterEvent'
...rfaceArcHUD3-classic\Rings\PowerTemplate.lua:76: in function `OnModuleEnable'
ArcHUD3-classic\ModuleCore.lua:133: in function <ArcHUD3-classic\ModuleCore.lua:112>
[C]: ?
...s\ArcHUD3-classic\Libs\AceAddon-3.0\AceAddon-3.0-12.lua:70: in function <...s\ArcHUD3-classic\Libs\AceAddon-3.0\AceAddon-3.0.lua:65>
...s\ArcHUD3-classic\Libs\AceAddon-3.0\AceAddon-3.0-12.lua:527: in function <...s\ArcHUD3-classic\Libs\AceAddon-3.0\AceAddon-3.0.lua:520>
(tail call): ?
ArcHUD3-classic\ModuleCore.lua:184: in function `?'
...sic\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:119: in function
<...sic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[C]: ?
...
ArcHUD3-classic\Core.lua:236: in function <ArcHUD3-classic\Core.lua:195>
[C]: ?
...s\ArcHUD3-classic\Libs\AceAddon-3.0\AceAddon-3.0-12.lua:70: in function <...s\ArcHUD3-classic\Libs\AceAddon-3.0\AceAddon-3.0.lua:65>
...s\ArcHUD3-classic\Libs\AceAddon-3.0\AceAddon-3.0-12.lua:527: in function `EnableAddon'
...s\ArcHUD3-classic\Libs\AceAddon-3.0\AceAddon-3.0-12.lua:620: in function <...s\ArcHUD3-classic\Libs\AceAddon-3.0\AceAddon-3.0.lua:605>
[C]: in function `LoadAddOn'
FrameXML\UIParent.lua:353: in function `UIParentLoadAddOn'
FrameXML\UIParent.lua:380: in function `CombatLog_LoadUI'
FrameXML\UIParent.lua:695: in function <FrameXML\UIParent.lua:658>
[C]: ?
```
and
```
3x [ADDON_ACTION_BLOCKED] AddOn 'ArcHUD3-classic' tried to call the protected function 'XPerl_PlayerbuffFrameAuraButton1:ClearAllPoints()'.
!BugGrabber\BugGrabber.lua:519: in function <!BugGrabber\BugGrabber.lua:519>
[C]: in function `ClearAllPoints'
FrameXML\SecureGroupHeaders.lua:753: in function <FrameXML\SecureGroupHeaders.lua:728>
FrameXML\SecureGroupHeaders.lua:1046: in function `SecureAuraHeader_Update'
FrameXML\SecureGroupHeaders.lua:686: in function <FrameXML\SecureGroupHeaders.lua:682>

Locals:
InCombatSkipped
```
Z-perl hasn't been officially updated yet for Classic, so I'm not sure if that's actually contributing to the second issue. I'm clueless about coding so I apologize in advance if these are somehow irrelevant.

**Comment by nyyr** [comment]
Let me guess, you are playing a Shadow Priest? The first issue should be fixed with classic-v5.0.11. As for the second, I guess this is because of X-/Z-Perl. Are you seeing this error with Z-Perl disable, too?

**Comment by Villainess** [comment]
I know the first error occurs on at least 3 classes: Priest (disc), Mage, and Druid (two of which don't even points in more than 1 tree). I would have to check if it happens others.

The second error does not occur if Z-perl is disabled, and vice-versa is also true; While ARCHUD is enabled, it seems to remove buffs from the Z-perl player frame and leave gaps between what remains.

**Comment by DDCorkum** [comment]
Good day,

On a hunch, #45 will fix the second-half of this.

"XPerl_PlayerbuffFrame**Aura**Button1:ClearAllPoints()" could be tainted because of the UnitAura issue that I discovered.  That error in #45 would have caused mayhem to any secure unit frame addon, such as CTMod (my own that I did troubleshooting with) or XPerl (the one you are using).

It appears my fix was accepted, so I do believe you can expect this to be better soon once the code is distributed.

**Comment by Villainess** [comment]
Awesome news! Thanks so much for looking into it.
