### ISSUE TITLE
Mana bar when in cat/bear form

### ISSUE THREAD

**Issue by giulianisanches** [nyyr/ArcHUD3#49]
Hi,

Is it possible to define custom bars to show my mana while i'm in some of my forms like cat/bear forms (druid) ?

Currently when i shapeshift my power bar change to rage/energy bar and i like to keep track of my mana.

Thanks.

**Comment by nyyr** [comment]
It's not possible with custom buff arcs, I will need to create a new ring. Should be no big deal, but I currently do not have a druid with cat form to test. I'll look into it anyway.

**Comment by giulianisanches** [comment]
I'm up to test it for you.

Albeit being a sort of programmer (i'm mostly a infra-as-a-code programmer), i don't know lua and wow api at all, but maybe i will be able to help in some way.

**Comment by nyyr** [comment]
Thanks. Can you check if it works with the current release (v5.0.13 / classic-v5.0.13)? There is a new ring available called "Druid: Mana (Cat/Bear Form)", but it is disabled by default. Thus, please enable it in ArcHUD's ring settings first.

**Comment by giulianisanches** [comment]
I have tried it before, and didn't saw any change.
I will check again later (after 9 PM BRT time) and let you know.

**Comment by giulianisanches** [comment]
Hey @nyyr , it worked!. I don't know if this bar existed before or i did something wrong before. Thank you.

**Comment by nyyr** [comment]
No, this bar was added in v5.0.13. Enjoy!
