### ISSUE TITLE
TBC Era Errors

### ISSUE THREAD

**Issue by perringaiden** [nyyr/ArcHUD3#56]
5x ArcHUD3-classic\Core.lua:23: attempt to index field 'LibClassicCasterino' (a nil value)
[string "@ArcHUD3-classic\Core.lua"]:23: in function <ArcHUD3-classic\Core.lua:22>
[string "@ArcHUD3-classic\Rings\Casting.lua"]:139: in function `?'
[string "@ArcHUD3-classic\RingTemplate.lua"]:1186: in function <ArcHUD3-classic\RingTemplate.lua:1182>

Locals:
unit = "player"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'LibClassicCasterino' (a nil value)"

3x ArcHUD3-classic\Rings\CustomBuff.lua:13: attempt to index local 'LibClassicDurations' (a nil value)
[string "@ArcHUD3-classic\Rings\CustomBuff.lua"]:13: in main chunk

Locals:
LM = <table> {
 Authors = "Authors"
 ManaShadowPriest = "Priest: Mana (Shadow Priest)"
 PetHealth = "Pet Health"
 SIDE = <table> {
 }
 TOOLTIP = <table> {
 }
 PetPower = "Pet Power"
 ManaDruid = "Druid: Mana (Cat/Bear Forms)"
 FocusCasting = "Focus Casting"
 ManaElementalShaman = "Shaman: Mana (Elemental/Enhancement Shaman)"
 TEXT = <table> {
 }
 FONT = "FRIZQT__.TTF"
 TargetHealth = "Target Health"
 ComboPoints = "Rogue: Combo Points"
 ManaBalanceDruid = "Druid: Mana (Balance Druid)"
 Runes = "Death Knight: Runes"
 TargetCasting = "Target Casting"
 FocusPower = "Focus Power"
 Power = "Player Power"
 HolyPower = "Paladin: Holy Power"
 SoulShards = "Warlock: Soul Shards"
 Version = "Version"
 Chi = "Monk: Chi"
 Stagger = "Monk: Stagger"
 FocusHealth = "Focus Health"
 Health = "Player Health"
 ComboPointsDruid = "Druid: Combo Points"
 MirrorTimer = "Mirror Timer"
 Casting = "Player Casting"
 ArcaneCharges = "Mage: Arcane Charges"
 TargetPower = "Target Power"
}
AceAddon = <table> {
 DisableAddon = <function> defined @ArcHUD3-classic\Libs\AceAddon-3.0\AceAddon-3.0.lua:555
 EnableAddon = <function> defined @ArcHUD3-classic\Libs\AceAddon-3.0\AceAddon-3.0.lua:520
 EmbedLibrary = <function> defined @ArcHUD3-classic\Libs\AceAddon-3.0\AceAddon-3.0.lua:186
 InitializeAddon = <function> defined @ArcHUD3-classic\Libs\AceAddon-3.0\AceAddon-3.0.lua:497
 IterateAddonStatus = <function> defined @ArcHUD3-classic\Libs\AceAddon-3.0\AceAddon-3.0.lua:597
 EmbedLibraries = <function> defined @ArcHUD3-classic\Libs\AceAddon-3.0\AceAddon-3.0.lua:168
 initializequeue = <table> {
 }
 statuses = <table> {
 }
 GetAddon = <function> defined @ArcHUD3-classic\Libs\AceAddon-3.0\AceAddon-3.0.lua:153
 NewAddon = <function> defined @ArcHUD3-classic\Libs\AceAddon-3.0\AceAddon-3.0.lua:105
 IterateModulesOfAddon = <function> defined @ArcHUD3-classic\Libs\AceAddon-3.0\AceAddon-3.0.lua:602
 IterateEmbedsOnAddon = <function> defined @ArcHUD3-classic\Libs\AceAddon-3.0\AceAddon-3.0.lua:601
 embeds = <table> {
 }
 IterateAddons = <function> defined @ArcHUD3-classic\Libs\AceAddon-3.0\AceAddon-3.0.lua:587
 frame = AceAddon30Frame {
 }
 addons = <table> {
 }
 enablequeue = <table> {
 }
}
AceConfigRegistry = <table> {
 RegisterOptionsTable = <function> defined @!KalielsTracker\Libs\AceConfig-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0.lua:315
 validated = <table> {
 }
 tables = <table> {
 }
 callbacks = <table> {
 }
 RegisterCallback = <function> defined @!KalielsTracker\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 GetOptionsTable = <function> defined @!KalielsTracker\Libs\AceConfig-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0.lua:360
 UnregisterCallback = <function> defined @!KalielsTracker\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 IterateOptionsTables = <function> defined @!KalielsTracker\Libs\AceConfig-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0.lua:346
 NotifyChange = <function> defined @!KalielsTracker\Libs\AceConfig-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0.lua:289
 ValidateOptionsTable = <function> defined @!KalielsTracker\Libs\AceConfig-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0.lua:276
 UnregisterAllCallbacks = <function> defined @!KalielsTracker\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
}
LibClassicDurations = nil
UnitAura = <function> defined =[C]:-1
(*temporary) = nil
(*temporary) = nil
(*temporary) = "LibClassicDurations"
(*temporary) = true
(*temporary) = nil
(*temporary) = "attempt to index local 'LibClassicDurations' (a nil value)"

**Comment by monstru1234** [comment]
i confirm the same error after the pre-patch for tbc

**Comment by joaomcarlos** [comment]
Could you release an update to fix this? 

I love this addon.

**Comment by khan5tar** [comment]
Been having a bug where the castbar isnt showing. Not sure about coding wise errors but i'd love for this to be fixed if possible. thank you

**Comment by bearguo** [comment]
> Could you release an update to fix this?
> 
> I love this addon.
The bug is caused by the version of libs. 

> Been having a bug where the castbar isnt showing. Not sure about coding wise errors but i'd love for this to be fixed if possible. thank you

The bug is caused by two libs the addon used.
 Just change _WOW_PROJECT_CLASSIC_ to _WOW_PROJECT_BURNING_CRUSADE_CLASSIC_  in **ArcHUD3-classic\Libs\LibClassicCasterino\LibClassicCasterino.lua:5** and **ArcHUD3-classic\Libs\LibClassicDurations\core.lua:20**
![Snipaste_2021-06-08_05-57-46](https://user-images.githubusercontent.com/20483603/121092654-7c01d100-c81e-11eb-972a-7ae97032c12f.png)
![Snipaste_2021-06-08_05-57-24](https://user-images.githubusercontent.com/20483603/121092658-7d32fe00-c81e-11eb-9796-f9df82977e3c.png)

**Comment by khan5tar** [comment]
That worked. Ty so much!

**Comment by Taresgos** [comment]
> > Could you release an update to fix this?
> > I love this addon.
> 
> > Been having a bug where the castbar isnt showing. Not sure about coding wise errors but i'd love for this to be fixed if possible. thank you
> 
> The bug is caused by two libs the addon used.
> Just change _WOW_PROJECT_CLASSIC_ to _WOW_PROJECT_BURNING_CRUSADE_CLASSIC_ in **ArcHUD3-classic\Libs\LibClassicCasterino\LibClassicCasterino.lua:5** and **ArcHUD3-classic\Libs\LibClassicDurations\core.lua:20**
> ![Snipaste_2021-06-08_05-57-46](https://user-images.githubusercontent.com/20483603/121092654-7c01d100-c81e-11eb-972a-7ae97032c12f.png)
> ![Snipaste_2021-06-08_05-57-24](https://user-images.githubusercontent.com/20483603/121092658-7d32fe00-c81e-11eb-9796-f9df82977e3c.png)

Thank you. Actually i gone further and deleted LibClassicDurations at all, because the author says it is classic-only and BC doesnt need it. And now archud with castbar work once again!

**Comment by bearguo** [comment]
> > > Could you release an update to fix this?
> > > I love this addon.
> > 
> > 
> > > Been having a bug where the castbar isnt showing. Not sure about coding wise errors but i'd love for this to be fixed if possible. thank you
> > 
> > 
> > The bug is caused by two libs the addon used.
> > Just change _WOW_PROJECT_CLASSIC_ to _WOW_PROJECT_BURNING_CRUSADE_CLASSIC_ in **ArcHUD3-classic\Libs\LibClassicCasterino\LibClassicCasterino.lua:5** and **ArcHUD3-classic\Libs\LibClassicDurations\core.lua:20**
> > ![Snipaste_2021-06-08_05-57-46](https://user-images.githubusercontent.com/20483603/121092654-7c01d100-c81e-11eb-972a-7ae97032c12f.png)
> > ![Snipaste_2021-06-08_05-57-24](https://user-images.githubusercontent.com/20483603/121092658-7d32fe00-c81e-11eb-9796-f9df82977e3c.png)
> 
> Thank you. Actually i gone further and deleted LibClassicDurations at all, because the author says it is classic-only and BC doesnt need it. And now archud with castbar work once again!

That's much better. Could you release a new version on the Curseforge ?
