### ISSUE TITLE
Wrath Classic Updates - DK Runes

### ISSUE THREAD

**Issue by rookdorf** [nyyr/ArcHUD3#62]
This addon mostly still works for Wrath Classic, but has a few bugs and is missing an appropriate implementation for DK Runes. 

I opened a [PR](https://github.com/nyyr/ArcHUD3/pull/61) for most of these, but left out DK Runes, which I have working on [another branch](https://github.com/adavis9592/ArcHUD3/tree/classic-wotlk-runes). It works fine, but is missing custom colors, rune orders, and sorting, so should probably get some updates to get it in line with the rest of the addon before merging in directly.

**Comment by bluedoomcapZZang** [comment]
리치 왕의 분노 클래식 업데이트 요청 합니다.

**Comment by rookdorf** [comment]
이것도 룬을 포함합니다: https://github.com/nyyr/ArcHUD3/pull/65
