### ISSUE TITLE
ComboPoints Ring not showing up after switch to Cat Form

### ISSUE THREAD

**Issue by WP7Joey** [nyyr/ArcHUD3#68]
Hello everybody,

first of all - i love this addon since the release. 

After the current Patch 10.0.5 I've got the issue mentioned in the headline. I'm unable to see the Combo Points Ring while in cat form. When I cancel the cat form, the combo point ring shows up and I can see my current Combo Points. The BlizzardUI doesn't show the combopoints while I'm not in cat form.

I think it is a problem with the "ComboPointsDruid.lua".

Any help is appreciated!

![Pic1_Cat](https://user-images.githubusercontent.com/123595529/214687114-de4f26ea-38c2-4c52-9409-e2fdcf8a23b2.png)
![Pic2_NoCat](https://user-images.githubusercontent.com/123595529/214687117-61311ef9-27c2-4e68-a35c-1a2274b5c804.png)

**Comment by WP7Joey** [comment]
These are the lua errors that I can grab with the addon buggrabber and bugsack.

![Lua-Errors](https://user-images.githubusercontent.com/123595529/214688374-817c4698-582c-421c-ad4a-b8bc29f320ed.jpeg)

**Comment by WP7Joey** [comment]
These are the lua errors that I can grab with the addon buggrabber and bugsack.

**Comment by WP7Joey** [comment]
These are the lua errors that I can grab with the addon buggrabber and bugsack.

![Lua-Errors](https://user-images.githubusercontent.com/123595529/214688583-4b5134eb-ab87-415c-a401-b00e3b1c84a4.jpeg)

**Comment by WP7Joey** [comment]
Sometime, when I spamclick on "Aktiviert" (activate) the combo points bar will show up but I don't know why...

![image](https://user-images.githubusercontent.com/123595529/214691342-f7995630-1c06-4e13-abf7-8b3c91a81443.png)

**Comment by rookdorf** [comment]
Just pushed the latest update, let me know if this is still happening

**Comment by LeoAscendat** [comment]
This is still happening

**Comment by senyaak** [comment]
I would like to try to fix it - any chance someone tried it already and have some heads-up? :)

**Comment by senyaak** [comment]
https://github.com/nyyr/ArcHUD3/pull/75 Would be nice if it could merged :)

**Comment by rookdorf** [comment]
Apologies, had this on my list but never got around to it. Thanks for the fix!
