### ISSUE TITLE
Create GH Action to auto-package/publish new versions

### ISSUE THREAD

**Issue by nyyr** [nyyr/ArcHUD3#70]
Goal: 

- Create a GH Action that uses https://github.com/BigWigsMods/packager to package and release a new version of ArcHUD3. 
- Packaging and release should only happen on new tags (see tag format for previous versions)

Tasks:

- [x] Integrate packager via GH actions
- [x] Publish package as GH release
- [x] Publish package to Curse
- [x] Publish package to WoWInterface
- [x] Do the same for ArcHUD3-classic

**Comment by nyyr** [comment]
@rookdorf Let's continue discussion here

> Yup, just merged! I don't have a lot of experience with GH actions, though I did use the BigWigs packager to make myself a local copy without doing the publish step. I think I ran into where I'd need the Curse key to push. Didn't try to automate anything yet though

Thanks!

If you already used the packager, then you are almost down - it should be easy with their provided GH action :) About the API keys: I can provide you those - I'll try to send you an e-mail.

**Comment by rookdorf** [comment]
Sounds good, I'll follow up on this in a couple days. Thanks for organizing!

**Comment by rookdorf** [comment]
Followed up via email, but here's a PR that should cover the project merge and get most of the action set up too: https://github.com/nyyr/ArcHUD3/pull/71

**Comment by rookdorf** [comment]
All done, new version published!
