### ISSUE TITLE
Addon conflict with World Quest Tracker #89

### ISSUE THREAD

**Issue by nyyr** [nyyr/ArcHUD3#9]
Kimoshi created this issue Sep 1, 2016

What steps will reproduce the problem?
1. Have both ArcHUD3 and World Quest Tracker enabled at the same time.
2. Talk to a flight master

What is the expected output? What do you see instead?
Expected output is nothing special. What happens is I get a huge FPS drop.

What version of the product are you using?
4.2.1 for ArcHUD3, r45 for World Quest Tracker.

Do you have an error log of what happened?
It spits out this LUA error when I talk to the flight master:
Message: ...rface\AddOns\WorldQuestTracker\WorldQuestTracker.lua:1598: <unnamed>:SetPoint(): Couldn't find region named '(null)'
Time: 09/01/16 10:59:37
Count: 1365
Stack: [C]: in function `SetPoint'
...rface\AddOns\WorldQuestTracker\WorldQuestTracker.lua:1598: in function `CreateZoneWidget'
...rface\AddOns\WorldQuestTracker\WorldQuestTracker.lua:4980: in function `GetOrCreateTaxyPOI'
...rface\AddOns\WorldQuestTracker\WorldQuestTracker.lua:5080: in function <...rface\AddOns\WorldQuestTracker\WorldQuestTracker.lua:5075>
[C]: in function `SetPinPosition'
...ns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:220: in function `ApplyCurrentPosition'
...ns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:137: in function `SetPosition'
...rd_SharedMapDataProviders\WorldQuestDataProvider.lua:152: in function `AddWorldQuest'
...rd_SharedMapDataProviders\WorldQuestDataProvider.lua:61: in function `RefreshAllData'
...rd_SharedMapDataProviders\WorldQuestDataProvider.lua:33: in function <...rd_SharedMapDataProviders\WorldQuestDataProvider.lua:33>
Interface\SharedXML\C_TimerAugment.lua:16: in function <Interface\SharedXML\C_TimerAugment.lua:14>

Locals: (*temporary) = <unnamed> {
0 = <userdata>
}
(*temporary) = "top"
(*temporary) = <table> {
SetDefaultModuleLibraries = <function> defined @Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua:398
Enable = <function> defined @Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua:325
UnregisterAllEvents = <function> defined @Interface\AddOns\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:200
EnableModule = <function> defined @Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua:363
modules = <table> {
}
GetModule = <function> defined @Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua:241
IterateEmbeds = <function> defined @Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua:473
defaultModuleLibraries = <table> {
}
options = <table> {
}
timer = 0
optionsTable = <table> {
}
defaultModuleState = true
SetDefaultModulePrototype = <function> defined @Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua:440
MIRROR_TIMER_START = <function> defined @Interface\AddOns\ArcHUD3\Rings\MirrorTimer.lua:119
name = "ArcHUD_MirrorTimer"
Initialize = <function> defined @Interface\AddOns\ArcHUD3\Rings\MirrorTimer.lua:34
IsEnabled = <function> defined @Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua:482
orderedModules = <table> {
}
localized = true
DisableModule = <function> defined @Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua:381
MIRROR_TIMER_STOP = <function> defined @Interface\AddOns\ArcHUD3\Rings\MirrorTimer.lua:179
timers = <table> {
}
Text = <table> {
}
f = ArcHUD_MirrorTimer_Ring {
}
RegisterMessage = <function> defined @Interface\AddOns\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:116
UnregisterMessage = <function> defined @Interface\AddOns\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:179
isInitialized = true
unit = "player"
baseName = "ArcHUD3"
PLAYER_ENTERING_WORLD = <function> defined @Interface\AddOns\ArcHUD3\Rings\MirrorTimer.lua:208
MIRROR_TIMER_PAUSE = <function> defined @Interface\AddOns\ArcHUD3\Rings\MirrorTimer.lua:171
IsModule = <function> defined @Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua:248
db = <table> {
}
SetDefaultModuleState = <function> defined @Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua:418
OnModuleEnable = <function> defined @Interface\AddOns\ArcHUD3\Rings\MirrorTimer.lua:93
version = "1.0 (r103)"
SetEnabledState = <function> defined @Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua:455
disableEvents = <table> {
}
enabledState = true
defaults = <table> {
}
RegisterEvent = <function> defined @Interface\AddOns\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:116
UnregisterAllMessages = <function> defined @Interface\AddOns\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:200
noAutoAlpha = true
OnModuleUpdate = <function> defined @Interface\AddOns\ArcHUD3\Rings\MirrorTimer.lua:47
NewModule =

Please provide any additional information below.
I'm not totally sure which addon is at fault for this, but I also notified World Quest Tracker's creator of this as well.

**Comment by nyyr** [comment]
Tercioo posted a comment Sep 1, 2016

World Quest Tracker author here, I think this issue is my fault. Looks like a bug on my AddOn where it tries to get the variable 'self' from the global namespace. Usually this would return NIL but ArcHUD3 are tagging the variable 'self' on the _G scope.

I'll fix this problem on my end, thank you!

**Comment by nyyr** [comment]
nyyr posted a comment Sep 1, 2016
Edit Delete

Thanks. A global self variable doesn't sound right. I'll look into it and see what I can do to avoid such conflicts in the future.

**Comment by Uruloke** [comment]
This should be fixed with commit 929637a926c6f6e2e530c19201c10be56a024310
